Repository Haltebogen/git-talk-server, pull requests merged in 2022-07, with the labels that each got.

#11 Refactor/build
  build.gradle
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/haltebogen/gittalk/controller/AuthController.java
  src/main/resources/application-local.yml
  src/test/java/com/haltebogen/gittalk/GitTalkApplicationTests.java
  src/test/java/com/haltebogen/gittalk/controller/MemberAPIControllerTest.java
  src/test/java/com/haltebogen/gittalk/init/InitInstance.java
  src/test/java/com/haltebogen/gittalk/service/MemberServiceTest.java
Labels: fix

#9 Swagger-ui 세팅
  build.gradle
  src/main/java/com/haltebogen/gittalk/config/SwaggerConfig.java
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/main/java/com/haltebogen/gittalk/controller/AuthController.java
  src/main/java/com/haltebogen/gittalk/controller/MemberAPIController.java
Labels: feature

#12 feat: MemberService에 getMembers method 추가
  src/main/java/com/haltebogen/gittalk/controller/MemberAPIController.java
  src/main/java/com/haltebogen/gittalk/dto/member/ChatMemberResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/GitUserProfileDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberDetailResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/oauth/GithubUserResponseDto.java
  src/main/java/com/haltebogen/gittalk/repository/MemberRepository.java
  src/main/java/com/haltebogen/gittalk/service/MemberService.java
Labels: feature

#13 refactor/profile
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/main/java/com/haltebogen/gittalk/controller/AuthController.java
  src/main/java/com/haltebogen/gittalk/controller/MemberAPIController.java
  src/main/java/com/haltebogen/gittalk/controller/OauthController.java
  src/main/java/com/haltebogen/gittalk/dto/member/ChatMemberResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/FollowRequestDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/FollowResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberCreateRequestDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberDetailResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberResponseDto.java
  src/main/java/com/haltebogen/gittalk/entity/user/Follow.java
  src/main/java/com/haltebogen/gittalk/entity/user/FollowStatus.java
  src/main/java/com/haltebogen/gittalk/entity/user/Member.java
  src/main/java/com/haltebogen/gittalk/entity/user/ProviderType.java
  src/main/java/com/haltebogen/gittalk/repository/FollowRepository.java
  src/main/java/com/haltebogen/gittalk/repository/MemberRepository.java
  src/main/java/com/haltebogen/gittalk/service/user/FollowService.java
  src/main/java/com/haltebogen/gittalk/service/user/MemberService.java
  src/main/java/com/haltebogen/gittalk/service/user/OAuthService.java
  src/main/resources/application-local.yml
  src/test/java/com/haltebogen/gittalk/controller/MemberAPIControllerTest.java
  src/test/java/com/haltebogen/gittalk/entity/MemberTest.java
  src/test/java/com/haltebogen/gittalk/init/InitInstance.java
  src/test/java/com/haltebogen/gittalk/repository/MemberRepositoryTest.java
  src/test/java/com/haltebogen/gittalk/service/MemberServiceTest.java
Labels: fix

#15 [deploy] Version 1.0.0
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  src/main/java/com/haltebogen/gittalk/GitTalkApplication.java
  src/main/java/com/haltebogen/gittalk/config/RestTemplateConfig.java
  src/main/java/com/haltebogen/gittalk/config/SwaggerConfig.java
  src/main/java/com/haltebogen/gittalk/config/WebConfig.java
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtTokenFilter.java
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtTokenProvider.java
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtValidationType.java
  src/main/java/com/haltebogen/gittalk/config/jwt/UserAuthentication.java
  src/main/java/com/haltebogen/gittalk/controller/AuthController.java
  src/main/java/com/haltebogen/gittalk/controller/MemberAPIController.java
  src/main/java/com/haltebogen/gittalk/controller/OauthController.java
  src/main/java/com/haltebogen/gittalk/dto/PaginationResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/ChatMemberResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/FollowRequestDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/FollowResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/GitUserProfileDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberCreateRequestDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberDetailResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/member/MemberResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/oauth/GithubUserResponseDto.java
  src/main/java/com/haltebogen/gittalk/dto/oauth/JwtTokenDto.java
  src/main/java/com/haltebogen/gittalk/dto/oauth/TokenDto.java
  src/main/java/com/haltebogen/gittalk/entity/BaseAuditEntity.java
  src/main/java/com/haltebogen/gittalk/entity/user/Follow.java
  src/main/java/com/haltebogen/gittalk/entity/user/FollowStatus.java
  src/main/java/com/haltebogen/gittalk/entity/user/Member.java
  src/main/java/com/haltebogen/gittalk/entity/user/ProviderType.java
  src/main/java/com/haltebogen/gittalk/repository/FollowRepository.java
  src/main/java/com/haltebogen/gittalk/repository/MemberRepository.java
  src/main/java/com/haltebogen/gittalk/response/ResponseHandler.java
  src/main/java/com/haltebogen/gittalk/service/user/FollowService.java
  src/main/java/com/haltebogen/gittalk/service/user/MemberService.java
  src/main/java/com/haltebogen/gittalk/service/user/OAuthService.java
  src/main/java/com/haltebogen/gittalk/trace/Trace.java
  src/main/java/com/haltebogen/gittalk/trace/TraceAspect.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.properties
  src/main/resources/templates/callback.mustache
  src/main/resources/templates/github.mustache
  src/test/java/com/haltebogen/gittalk/GitTalkApplicationTests.java
  src/test/java/com/haltebogen/gittalk/controller/MemberAPIControllerTest.java
  src/test/java/com/haltebogen/gittalk/dto/oauth/OauthDtoTest.java
  src/test/java/com/haltebogen/gittalk/entity/MemberTest.java
  src/test/java/com/haltebogen/gittalk/init/InitInstance.java
  src/test/java/com/haltebogen/gittalk/repository/MemberRepositoryTest.java
  src/test/java/com/haltebogen/gittalk/service/MemberServiceTest.java
  src/test/java/com/haltebogen/gittalk/service/OauthServiceTest.java
Labels: deploy

#17 refactor: githubUserResponseDto getFollowing error and Bean error
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/test/java/com/haltebogen/gittalk/service/MemberServiceTest.java
Labels: fix

#18 [hotfix] Version 1.0.0
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/test/java/com/haltebogen/gittalk/service/MemberServiceTest.java
Labels: deploy

#19 refactor: jwt secret key variable 구조 변경 및 JwtProvider env 값 변경
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtTokenProvider.java
Labels: fix

#20 [hotfix] Version 1.0.0
  src/main/java/com/haltebogen/gittalk/config/jwt/JwtTokenProvider.java
Labels: deploy

#22 chore: Add Chatting, Mongo DB config
  build.gradle
  src/main/java/com/haltebogen/gittalk/config/MongoConfig.java
  src/main/java/com/haltebogen/gittalk/config/WebSocketConfig.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatMessage.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatRoom.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatRoomMedia.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatRoomParticipant.java
  src/main/java/com/haltebogen/gittalk/entity/chat/MediaType.java
  src/main/java/com/haltebogen/gittalk/entity/chat/MessageAlertType.java
  src/main/java/com/haltebogen/gittalk/entity/chat/MessageStatus.java
  src/main/java/com/haltebogen/gittalk/util/ChatWebSocketHandler.java
  src/main/resources/application-local.yml
Labels: feature

#23 refactor: GitTalkApplicationTests ContextConfiguration annotation 설정 수정
  src/main/java/com/haltebogen/gittalk/config/WebSecurityConfig.java
  src/main/java/com/haltebogen/gittalk/controller/MemberAPIController.java
  src/main/java/com/haltebogen/gittalk/controller/OauthController.java
  src/main/java/com/haltebogen/gittalk/dto/member/SearchGithubFollowResponseDto.java
  src/main/java/com/haltebogen/gittalk/service/user/MemberService.java
  src/main/resources/application-local.yml
  src/main/resources/templates/github.mustache
  src/test/java/com/haltebogen/gittalk/GitTalkApplicationTests.java
Labels: feature

#24 refactor: chat-config refactoring
  src/main/java/com/haltebogen/gittalk/config/MongoConfig.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatMessage.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatRoom.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatRoomMedia.java
  src/main/java/com/haltebogen/gittalk/entity/chat/ChatRoomParticipant.java
  src/main/java/com/haltebogen/gittalk/service/user/MemberService.java
Labels: fix

#25 Feature/Github Follow Member Search API swagger document
  src/main/java/com/haltebogen/gittalk/controller/MemberAPIController.java
  src/main/java/com/haltebogen/gittalk/dto/member/SearchGithubFollowResponseDto.java
Labels: feature
